### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by lavajCN** [1ndev-ui/Action-ROM-Builder#1]
when i am running, there is an error, it says,"No space left on device"

**Comment by 1ndev-ui** [comment]
By default the workflow uses GitHub's runner, I highly recommend setting up a actions runner on your own cloud server and modifying the workflow to use your runner rather than Githubs.

**Comment by 1ndev-ui** [comment]
By default the workflow uses GitHub's runner.

I highly recommend setting up an actions runner on your own cloud server with the required specifications brought forth by the ROM's maintainers and then modifying the workflow to use your runner rather than githubs.
